services:
  nginx:
    build: nginx/docker/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "9001-9009:9001-9009"
    volumes:
      - ./certbot/:/etc/nginx/conf.d/certbot
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - infrador

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

  infrador:
    build: infrador.com/docker/
    container_name: infrador
    volumes:
      - ./infrador.com/public_html/:/var/www/html/
